### ISSUE TITLE
Strip _away from nicks

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#3]
We have
nick = nick.rstrip('_1234567890')
It might be good to also ignore _away occurring at the end of nicknames. Sometimes people might join the channel with that in their nick.

**Comment by qarkai** [comment]
Could you try c940c92?

**Comment by ilmari-lauhakangas** [comment]
It works, thank you!

**Comment by ilmari-lauhakangas** [comment]
@qarkai Based on some discussions, I started thinking of a more flexible way as people use other crap besides _away in their nicks.. I came up with this:

```
    if nick.endswith(('_away','_afk','_brb','_off')):
        nick = re.sub('\_.+$', '', nick)
```
So it checks the suffixes using a tuple. Then it substitutes the suffix with nothing with the help of a regex checking from the end of the string until and including an underscore.
I tested it and it seems to work (wow) :)

**Comment by qarkai** [comment]
@ilmari-lauhakangas I don't know if underscore is allowed in IRC nick. If yes then this code will cut everything after first underscore:
```
>>> re.sub(r'_.+$', '', 'my_nick_afk')
'my'
```
Also underscore is not a special character, it doesn't need to be escaped :)
I'd use something like
```
status = re.search('_(afk|away|brb|off)$', nick)
if status:
    nick = nick[:-len(status.group(0))]
```
or `nick = re.sub('{}$'.format(status.group(0)), '', nick)` in the last line.

**Comment by ilmari-lauhakangas** [comment]
Underscore is allowed in IRC nicks. Well, you can implement one of your solutions.

I mean, not the first code block, but either of the last two.

**Comment by qarkai** [comment]
Updated in 48716cb913045a7b0655c6ee266fb887e894d4ac.

**Comment by ilmari-lauhakangas** [comment]
Thanks :)
