### ISSUE TITLE
If someone other than a newcomer speaks into the channel, the bot still welcomes

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#4]
It seems your changes to the block https://github.com/qarkai/WelcomeBot/blob/Py3/bot.py#L235 broke the "silence feature" of the bot.

**Comment by qarkai** [comment]
Does it happen every time when someone (not a bot or newcomer) speaks? I can see following scenario:
1) newcomer joins channel;
2) 60 seconds later (bot wait time) somebody talks to channel;
3) bot notes that newcomer is around for enough time and welcomes him [here](https://github.com/qarkai/WelcomeBot/blob/Py3/bot.py#L350)
4) bot handles message [here](https://github.com/qarkai/WelcomeBot/blob/Py3/bot.py#L359)

I'll move welcoming after message handling. This should help and it has more sense imho.
Could you try 535d49c?

**Comment by ilmari-lauhakangas** [comment]
I had wait time as 120 seconds. I noticed two occasions, where there was discussion between a newcomer joining and bot welcoming. I will try it.

**Comment by ilmari-lauhakangas** [comment]
Nope, the bot still welcomes a new user, if I say something between join and wait-time finish.

**Comment by qarkai** [comment]
@ilmari-lauhakangas I see. Then I need to test. It's rather hard simulating several people in chat so I'm going to do it on weekend.

**Comment by ilmari-lauhakangas** [comment]
You can email me and we can team up, if you want. I usually just open a new instance of Kiwi IRC, eg. https://kiwiirc.com/client/irc.freenode.net/libreoffice-qa and join with a bogus new nick.

**Comment by qarkai** [comment]
Finally got here. After some research I can say: I don't know how and why silence feature was working even in original code. When not a newcomer (or bot) speaks to channel, bot searches for newcomers to process without welcoming them but can't select one since newcomer wasn't there long enough. I guess in this case we shouldn't check newcomer's presence time.

**Comment by qarkai** [comment]
Fixed in https://github.com/qarkai/WelcomeBot/commit/9bfaf8c8ca3f396c48bfc2e003134a36028a7915 Could you try it?

**Comment by ilmari-lauhakangas** [comment]
Yes, now my silencing test was successful :)
It might very well be true that the silence feature did not work in the original code. I remember various struggles when OpenHatch was using the bot.
