### ISSUE TITLE
User joins with unknown nick, switches to known nick and gets greeted with a numeric ID

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#5]
Steps:

1. Join with a nickname not in nicks list
2. Change nick to something that **is** in nicks list before being greeted by the bot

Bot will greet with a numeric ID.

Expected behaviour would be to skip the greeting in this case.

**Comment by qarkai** [comment]
Should be fixed in 47c835a.

**Comment by ilmari-lauhakangas** [comment]
Tested the fix and it worked. Thanks again!
