### ISSUE TITLE
Quit after disconnect (netsplit/k-line or any other)

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#6]
Currently, if WelcomeBot is kicked out (by a Freenode mistake, for example) or disconnected in a netsplit, the python process keeps running and unfortunately starts taking 100% CPU.

I looked at other bots and it seems the sane thing to do is exit without trying to reconnect. Re-running the program should be handled separately with a daemon or a shell script.

Reference: `https://github.com/ayust/kitnirc/issues/15#issuecomment-50968217` (formatted as code as I don't want to ping the issue..)

**Comment by qarkai** [comment]
Sorry for late response. Should be fixed in 2535fcb.

**Comment by ilmari-lauhakangas** [comment]
Thanks, dude. Bit of a late response on my part as well because I was at the LibO conf. Now I updated to the fix.
