### ISSUE TITLE
Remove person from newcomers, if they are kicked (with proposed solution)

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#8]
With the recent spamwave on freenode, I wanted Welcomebot to understand that kicked persons do not need to be welcomed :) Here is a solution that works for me:

```
    if ircmsg.find("KICK " + bot.channel) != -1:
        for person in bot.newcomers:
            if ircmsg.find("KICK " + bot.channel + " " + person.clean_nick) != -1:
                bot.newcomers.remove(person)
                break
```
If you have an idea to make it more concise, feel free to change!
As you can imagine, the raw message contains the string

`KICK #channel kickeduser`

...while the actor is the one who did the kicking.

Edit: now I realised the solution only worked, if I did the kicking, but it failed if IZBot did the kicking. I don't understand why the message seemed to be ignored as bot.known_bots is only handled in case of PRIVMSG and JOIN.

**Comment by ilmari-lauhakangas** [comment]
My mistake was using person.clean_nick. Correct way would be

```
    if ircmsg.find("KICK " + bot.channel) != -1:
        for person in bot.newcomers:
            if ircmsg.find("KICK " + bot.channel + " " + person.nick) != -1:
                bot.newcomers.remove(person)
                break
```

**Comment by qarkai** [comment]
Added check though not tested.

**Comment by ilmari-lauhakangas** [comment]
Thanks!
