### ISSUE TITLE
NickServ identification syntax and a need to wait for identification acknowledgement

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#9]
After registering my bot and trying out identification, I noticed two things.

1. The PRIVMSG syntax was missing a : immediately before IDENTIFY (spaces in parameter are disallowed otherwise)
2. I had to add a 10 second sleep after the NickServ identification message so it had time to be picked up (otherwise I was unable to join a channel that required users to be identified)

Here are my changes

```
            ircconn.send("PRIVMSG {} :{} {} {}".format("NickServ", "IDENTIFY", botnick, password))
            time.sleep(10)
    ircconn.send("JOIN {} \n".format(channel))  # Joins channel
```

The raw message for the freenode NickServ acknowledgement is

`:NickServ!NickServ@services. NOTICE LibO_welcome :You are now identified for LibO_welcome.`

Edit: probably a better way would be to start using [SASL authentication](https://bd808.com/blog/2017/03/01/sasl-auth-with-python-irc/).

**Comment by qarkai** [comment]
I consider porting to [irc.bot](https://github.com/jaraco/irc/blob/master/scripts/testbot.py) sometime later.

**Comment by ilmari-lauhakangas** [comment]
That would be cool :) Thanks for still caring!
